#workflow to build and push container
#called by other workflows
name: Reusable container build and push

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
      tagname:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Set image tag
      id: set_image_tag
      run: |
        if [[ "${{ inputs.tagname }}" == "main" ]]; then
          echo "tag_name=latest" >> $GITHUB_ENV
        else
          echo "tag_name=${{ inputs.tagname }}" >> $GITHUB_ENV
        fi
    - name: Docker Build, Tag & Push
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ inputs.imagename }}
        registry: docker.io
        tags: ${{ env.tag_name }}
        dockerfile: ${{ inputs.dockerfile }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}